# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UserInfoGraphQL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UserInfoGraphQL
  pod "Apollo"

  target 'UserInfoGraphQLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UserInfoGraphQLUITests' do
    # Pods for testing
  end

end
