# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Generics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Generics
  pod 'Alamofire', '~> 5.0.0-rc.3'

  target 'GenericsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GenericsUITests' do
    # Pods for testing
  end

end
